version: "3.9"

services:
  flight-app-client:
    container_name: "flight-app-client"
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      # external:internal
      - "8001:80"
    depends_on:
      - flight-app-server


  flight-app-server:
    container_name: "flight-app-server"
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      # external:internal
      - "8000:80"
    env_file:
      - ./server/.env
    environment:
      - ConnectionStrings:DefaultConnection=Host=flight-app-db:5432;Database=flight-app;Username=postgres;Password=postgres
    depends_on:
      - flight-app-db
  
  
  flight-app-db:
    container_name: "flight-app-db"
    image: "postgres:15.2-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      # external:internal
      - "5445:5432"
    volumes:
      - "flight-app-db-postgres-volume:/var/lib/postgresql/data"

volumes:
  flight-app-db-postgres-volume: